import CollisionIdeals.Basic
import CollisionIdeals.ConductorDescent
import CollisionIdeals.FiniteCompletion
import CollisionIdeals.FiberProduct
import CollisionIdeals.Planar
import CollisionIdeals.Secant
