import Mathlib.FieldTheory.Minpoly.IsIntegrallyClosed
import Mathlib.RingTheory.Conductor

/-!
# Monogenic order wiring for the secant--trace strategy

This file gives names to Mathlib's existing objects for a monogenic order
`B[alpha]` inside an overring `T`.  It is the finite hypersurface comparison
order used after an integral primitive generator has been chosen for the
secant--trace strategy.

No generator is chosen here, and no Tate reconstruction, conductor--trace
dual identity, or boundary landing statement is asserted.  In particular,
this remains part of the opt-in research layer.
-/

set_option autoImplicit false

namespace CollisionIdeals.Planar

noncomputable section

universe u v

variable (B : Type u) [CommRing B]
variable (T : Type v) [CommRing T] [Algebra B T]

/-- The monogenic `B`-order generated by `alpha` inside `T`. -/
abbrev monogenicOrder (alpha : T) : Subalgebra B T :=
  Algebra.adjoin B ({alpha} : Set T)

/-- The distinguished generator, regarded as an element of its monogenic order. -/
def monogenicOrderGenerator (alpha : T) : monogenicOrder B T alpha :=
  ⟨alpha, Algebra.subset_adjoin (Set.mem_singleton alpha)⟩

@[simp]
theorem monogenicOrderGenerator_coe (alpha : T) :
    (monogenicOrderGenerator B T alpha : T) = alpha :=
  rfl

section IntegralGenerator

variable [IsDomain B] [IsDomain T] [NoZeroSMulDivisors B T]
variable [IsIntegrallyClosed B]

/-- Mathlib's canonical power basis on the integral monogenic order. -/
def monogenicOrderPowerBasis (alpha : T) (halpha : IsIntegral B alpha) :
    PowerBasis B (monogenicOrder B T alpha) :=
  Algebra.adjoin.powerBasis' halpha

@[simp]
theorem monogenicOrderPowerBasis_gen
    (alpha : T) (halpha : IsIntegral B alpha) :
    (monogenicOrderPowerBasis B T alpha halpha).gen =
      monogenicOrderGenerator B T alpha := by
  exact Algebra.adjoin.powerBasis'_gen halpha

/-- The monogenic order is finite as a module over its base. -/
theorem monogenicOrder_moduleFinite
    (alpha : T) (halpha : IsIntegral B alpha) :
    Module.Finite B (monogenicOrder B T alpha) := by
  exact Module.Finite.of_basis
    (monogenicOrderPowerBasis B T alpha halpha).basis

/-- The monogenic order is free as a module over its base. -/
theorem monogenicOrder_moduleFree
    (alpha : T) (halpha : IsIntegral B alpha) :
    Module.Free B (monogenicOrder B T alpha) := by
  exact Module.Free.of_basis
    (monogenicOrderPowerBasis B T alpha halpha).basis

/-- The canonical hypersurface presentation of an integral monogenic order. -/
def monogenicOrderEquivAdjoinRoot
    (alpha : T) (halpha : IsIntegral B alpha) :
    AdjoinRoot (minpoly B alpha) ≃ₐ[B] monogenicOrder B T alpha :=
  minpoly.equivAdjoin halpha

/-- The derivative of the defining minimal polynomial evaluated at the generator. -/
def monogenicOrderJacobian (alpha : T) : T :=
  Polynomial.aeval alpha (Polynomial.derivative (minpoly B alpha))

/-- The same Jacobian element, retained in the monogenic order. -/
def monogenicOrderJacobianInOrder (alpha : T) :
    monogenicOrder B T alpha :=
  ⟨monogenicOrderJacobian B T alpha,
    Polynomial.aeval_mem_adjoin_singleton B alpha⟩

omit [IsDomain B] [IsDomain T] [NoZeroSMulDivisors B T]
  [IsIntegrallyClosed B] in
@[simp]
theorem monogenicOrderJacobianInOrder_coe (alpha : T) :
    (monogenicOrderJacobianInOrder B T alpha : T) =
      monogenicOrderJacobian B T alpha :=
  rfl

end IntegralGenerator

/-- The conductor of `B[alpha]` in `T`, using Mathlib's existing definition. -/
abbrev monogenicOrderConductor (alpha : T) : Ideal T :=
  conductor B alpha

theorem mem_monogenicOrderConductor_iff (alpha s : T) :
    s ∈ monogenicOrderConductor B T alpha ↔
      ∀ t : T, s * t ∈ monogenicOrder B T alpha :=
  mem_conductor_iff

/-- Every conductor element already belongs to the monogenic order. -/
theorem monogenicOrderConductor_subset_order (alpha : T) :
    (monogenicOrderConductor B T alpha : Set T) ⊆
      monogenicOrder B T alpha :=
  conductor_subset_adjoin

end

end CollisionIdeals.Planar
