import CollisionIdeals.JacobianConjecture
import CollisionIdeals.Planar.ConjugateBoundary
import CollisionIdeals.Planar.Secant

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

/-- A polynomial self-map of the complex affine plane. -/
abbrev PlanarPolynomialMap :=
  Fin 2 → PlanePolynomial

/--
The two-dimensional Jacobian conjecture, with the Keller hypothesis
displayed explicitly.
-/
def JacobianConjectureTwo : Prop :=
  ∀ F : PlanarPolynomialMap,
    IsPlanarKeller F →
      IsPolynomialAutomorphism F

theorem jacobianConjectureTwo_iff_planarJacobianConjecture :
    JacobianConjectureTwo ↔ PlanarJacobianConjecture :=
  Iff.rfl

/--
The canonical planar collision idempotent `q_F`.

For a Keller map it is the secant projector constructed from the constant
Jacobian determinant.  Away from the Keller locus its value is defined to
be zero, so the public object depends only on `F`, not on a chosen proof of
the Keller condition.
-/
noncomputable def planarCollisionIdempotent
    (F : PlanarPolynomialMap) :
    CollisionRing F := by
  classical
  exact
    if hKeller : IsPlanarKeller F then
      Classical.choose
        (exists_collisionOffDiagonalProjector_of_isPlanarKeller
          F hKeller)
    else
      0

/-- On the Keller locus, `q_F` is the collision off-diagonal projector. -/
theorem planarCollisionIdempotent_isProjector
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    IsCollisionOffDiagonalProjector F
      (planarCollisionIdempotent F) := by
  simp only [planarCollisionIdempotent, dif_pos hKeller]
  exact
    Classical.choose_spec
      (exists_collisionOffDiagonalProjector_of_isPlanarKeller
        F hKeller)

/-- The collision idempotent satisfies `q_F² = q_F`. -/
theorem planarCollisionIdempotent_sq
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    planarCollisionIdempotent F *
        planarCollisionIdempotent F =
      planarCollisionIdempotent F :=
  (planarCollisionIdempotent_isProjector F hKeller).1

/--
The kernel of `bar μ_F` is the principal ideal generated by `q_F`.
-/
theorem ker_barMu_eq_span_planarCollisionIdempotent
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    RingHom.ker (barMu F) =
      Ideal.span {planarCollisionIdempotent F} := by
  rw [collisionDiagonalMap_ker]
  exact
    (planarCollisionIdempotent_isProjector F hKeller).2

/-- The canonical projector vanishes exactly when `bar μ_F` is injective. -/
theorem planarCollisionIdempotent_eq_zero_iff_ker_barMu_eq_bot
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    planarCollisionIdempotent F = 0 ↔
      RingHom.ker (barMu F) = ⊥ := by
  rw [ker_barMu_eq_span_planarCollisionIdempotent F hKeller,
    Ideal.span_singleton_eq_bot]

/--
Kernel vanishing is exactly equality of the collision and diagonal ideals.
-/
theorem ker_barMu_eq_bot_iff_collisionIdeal_eq_diagonalIdeal
    (F : PlanarPolynomialMap) :
    RingHom.ker (barMu F) = ⊥ ↔
      collisionIdeal F =
        diagonalIdeal (R := ℂ) (ι := Fin 2) :=
  collisionDiagonalMap_ker_eq_bot_iff F

namespace PlanarRigidity

variable {F : PlanarPolynomialMap}
variable {N : Type} [Field N]
variable [Algebra (PlanarBaseFunctionField F) N]

/--
The exact hidden-inertia package consumed by planar rigidity.

The Keller hypothesis is part of the package from the outset.  The last
three fields expose the final geometric chain without collapsing it into
one contrapositive hypothesis: visible sheets kill divisorial inertia,
purity promotes this to étaleness, and finite-étale rigidity trivializes
the normal closure.
-/
structure HiddenInertiaConfiguration where
  hKeller : IsPlanarKeller F
  cover : PlanarNormalizedCover (F := F) (N := N)
  inertia : PlanarValuationInertiaFamily cover
  visibility : PlanarConjugateOpenVisibility inertia
  purity : inertia.DivisorialPurity
  finiteEtaleRigidity : cover.FiniteEtaleRigidity
  detectsInertia :
    visibility.DetectsInertia

namespace HiddenInertiaConfiguration

variable (C : HiddenInertiaConfiguration (F := F) (N := N))

include C in
/-- Hidden-inertia detection leaves no nontrivial divisorial inertia. -/
theorem noNontrivialDivisorialInertia :
    C.inertia.NoNontrivialDivisorialInertia :=
  C.visibility.divisor_isEmpty_of_detectsInertia
    C.detectsInertia

/--
`PlanarRigidity`: a hidden-inertia configuration forces `N = K`.

Visible-sheet detection first kills divisorial inertia.  Purity makes the
finite normalization étale, and affine-plane finite-étale rigidity makes
the cover trivial.  The conclusion is surjectivity of the canonical field
embedding, the type-correct proposition expressing `N = K`.
-/
theorem normalClosureExtension_trivial :
    C.cover.normalClosure.ExtensionTrivial :=
  C.inertia.normalClosureExtension_trivial_of_noNontrivialDivisorialInertia
    C.noNontrivialDivisorialInertia
    C.purity
    C.finiteEtaleRigidity

include C in
/-- Triviality of the normal closure immediately forces `L = K`. -/
theorem functionFieldExtension_trivial :
    PlanarFunctionFieldExtensionTrivial F :=
  C.cover.normalClosure.functionFieldExtensionTrivial_of_extensionTrivial
    C.normalClosureExtension_trivial

/-- The algebra isomorphism form of the conclusion `N = K`. -/
noncomputable def normalClosureEquivBase :
    PlanarBaseFunctionField F ≃ₐ[PlanarBaseFunctionField F] N :=
  C.cover.normalClosure.extensionEquivBase
    C.normalClosureExtension_trivial

end HiddenInertiaConfiguration

end PlanarRigidity

/--
The three formal consequences requested from planar rigidity.
-/
structure PlanarRigidityConclusion
    (F : PlanarPolynomialMap) where
  collisionIdempotent_eq_zero :
    planarCollisionIdempotent F = 0
  collisionIdeal_eq_diagonalIdeal :
    collisionIdeal F =
      diagonalIdeal (R := ℂ) (ι := Fin 2)
  isPolynomialAutomorphism :
    IsPolynomialAutomorphism F

/--
The end-to-end conclusion for one hidden-inertia configuration.

The only inputs after rigidity are the generic-degree-one collision bridge
and the classical Ax--Grothendieck automorphism interface.
-/
theorem PlanarRigidity.HiddenInertiaConfiguration.conclusion
    {F : PlanarPolynomialMap}
    {N : Type} [Field N]
    [Algebra (PlanarBaseFunctionField F) N]
    (C : PlanarRigidity.HiddenInertiaConfiguration
      (F := F) (N := N))
    (hGeneric : PlanarGenericDegreeOneExcludesOffDiagonal)
    (hAx : PlanarAxGrothendieck) :
    PlanarRigidityConclusion F := by
  have hNormalClosure :
      C.cover.normalClosure.ExtensionTrivial :=
    C.normalClosureExtension_trivial
  have hFunctionField :
      PlanarFunctionFieldExtensionTrivial F :=
    PlanarNormalClosureData.functionFieldExtensionTrivial_of_extensionTrivial
      C.cover.normalClosure hNormalClosure
  have hObstruction :
      obstructionIdeal F = ⊥ :=
    obstructionIdeal_eq_bot_of_planarFunctionField_trivial
      hGeneric F C.hKeller hFunctionField
  have hKernel :
      RingHom.ker (barMu F) = ⊥ := by
    rw [collisionDiagonalMap_ker]
    exact hObstruction
  have hIdempotent :
      planarCollisionIdempotent F = 0 :=
    (planarCollisionIdempotent_eq_zero_iff_ker_barMu_eq_bot
      F C.hKeller).2 hKernel
  have hIdeals :
      collisionIdeal F =
        diagonalIdeal (R := ℂ) (ι := Fin 2) :=
    (ker_barMu_eq_bot_iff_collisionIdeal_eq_diagonalIdeal F).1
      hKernel
  have hAutomorphism :
      IsPolynomialAutomorphism F :=
    (planarPolynomialAutomorphism_iff_obstructionIdeal_eq_bot
      hAx F).2 hObstruction
  exact ⟨hIdempotent, hIdeals, hAutomorphism⟩

/--
Canonical-idempotent planar vanishing implies the two-dimensional
Jacobian conjecture, modulo the explicit Ax--Grothendieck interface.
-/
theorem planarVanishing_implies_jc2
    (hAx : PlanarAxGrothendieck)
    (hvan :
      ∀ F : PlanarPolynomialMap,
        IsPlanarKeller F →
          planarCollisionIdempotent F = 0) :
    JacobianConjectureTwo := by
  intro F hKeller
  have hker :
      RingHom.ker (barMu F) = ⊥ :=
    (planarCollisionIdempotent_eq_zero_iff_ker_barMu_eq_bot
      F hKeller).1
      (hvan F hKeller)
  have hIdeals :
      collisionIdeal F =
        diagonalIdeal (R := ℂ) (ι := Fin 2) :=
    (ker_barMu_eq_bot_iff_collisionIdeal_eq_diagonalIdeal F).1
      hker
  exact
    (planarPolynomialAutomorphism_iff_obstructionIdeal_eq_bot
      hAx F).2
      ((obstructionIdeal_eq_bot_iff F).2 hIdeals)

end

end CollisionIdeals
