import CollisionIdeals.AutomorphismCriterion
import CollisionIdeals.Planar.Endgame
import CollisionIdeals.Planar.Secant

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

/--
The planar collision idempotent `q_F`, constructed on the Keller locus.

The Keller certificate is an explicit argument: there is no artificial
choice of the zero idempotent away from the locus on which the
off-diagonal projector has been constructed.
-/
noncomputable def planarCollisionIdempotent
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    CollisionRing F :=
  Classical.choose
    (exists_collisionOffDiagonalProjector_of_isPlanarKeller
      F hKeller)

/-- The chosen planar idempotent is the collision off-diagonal projector. -/
theorem planarCollisionIdempotent_isProjector
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    IsCollisionOffDiagonalProjector F
      (planarCollisionIdempotent F hKeller) :=
  Classical.choose_spec
    (exists_collisionOffDiagonalProjector_of_isPlanarKeller
      F hKeller)

/-- The collision idempotent satisfies `q_F² = q_F`. -/
theorem planarCollisionIdempotent_sq
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    planarCollisionIdempotent F hKeller *
        planarCollisionIdempotent F hKeller =
      planarCollisionIdempotent F hKeller :=
  (planarCollisionIdempotent_isProjector F hKeller).1

/-- The kernel of `bar μ_F` is the ideal generated by `q_F`. -/
theorem ker_barMu_eq_span_planarCollisionIdempotent
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    RingHom.ker (barMu F) =
      Ideal.span {planarCollisionIdempotent F hKeller} := by
  rw [collisionDiagonal_ker]
  exact
    (planarCollisionIdempotent_isProjector F hKeller).2

/-- The projector vanishes exactly when `bar μ_F` is injective. -/
theorem planarCollisionIdempotent_eq_zero_iff_ker_barMu_eq_bot
    (F : PlanarPolynomialMap)
    (hKeller : IsPlanarKeller F) :
    planarCollisionIdempotent F hKeller = 0 ↔
      RingHom.ker (barMu F) = ⊥ := by
  rw [ker_barMu_eq_span_planarCollisionIdempotent F hKeller,
    Ideal.span_singleton_eq_bot]

namespace Planar

namespace PlanarKellerCollisionModel

variable {F : PlanarPolynomialMap}

/--
The planar divisorial endgame kills the chosen off-diagonal idempotent.

The concrete Keller collision model and the global no-hidden-inertia
hypothesis are displayed as separate inputs.
-/
theorem collisionIdempotent_eq_zero
    (M : PlanarKellerCollisionModel F)
    (hNoHidden :
      letI : Field M.N := M.fieldN
      letI : Algebra (PlanarBaseFunctionField F) M.N :=
        M.algebraN
      PlanarNoHiddenInertia M.diagram) :
    planarCollisionIdempotent F M.keller = 0 := by
  apply
    (planarCollisionIdempotent_eq_zero_iff_ker_barMu_eq_bot
      F M.keller).2
  rw [collisionDiagonal_ker]
  exact
    planarVanishing_assuming_standardGeometry M hNoHidden

/--
The same divisorial endgame identifies the collision and diagonal ideals.
-/
theorem collisionIdeal_eq_diagonalIdeal
    (M : PlanarKellerCollisionModel F)
    (hNoHidden :
      letI : Field M.N := M.fieldN
      letI : Algebra (PlanarBaseFunctionField F) M.N :=
        M.algebraN
      PlanarNoHiddenInertia M.diagram) :
    collisionIdeal F =
      diagonalIdeal (R := ℂ) (ι := Fin 2) := by
  exact
    (obstructionIdeal_eq_bot_iff F).1
      (planarVanishing_assuming_standardGeometry M hNoHidden)

/--
With Ax--Grothendieck supplied by the literature interface, the
planar divisorial endgame makes the Keller map a polynomial automorphism.
-/
theorem isPolynomialAutomorphism
    (M : PlanarKellerCollisionModel F)
    (hNoHidden :
      letI : Field M.N := M.fieldN
      letI : Algebra (PlanarBaseFunctionField F) M.N :=
        M.algebraN
      PlanarNoHiddenInertia M.diagram) :
    IsPolynomialAutomorphism F :=
  planarAutomorphism_assuming_externalLiterature M hNoHidden

end PlanarKellerCollisionModel

end Planar

end

end CollisionIdeals
