import CollisionIdeals.NormalizationModel
import CollisionIdeals.Planar.Basic
import CollisionIdeals.PolynomialFiberProduct
import Mathlib.Algebra.Group.Subgroup.Pointwise
import Mathlib.Algebra.GCDMonoid.IntegrallyClosed
import Mathlib.AlgebraicGeometry.Morphisms.OpenImmersion
import Mathlib.FieldTheory.Galois.Basic
import Mathlib.FieldTheory.Normal.Closure
import Mathlib.FieldTheory.Perfect
import Mathlib.RingTheory.IntegralClosure.IntegrallyClosed
import Mathlib.RingTheory.Localization.FractionRing
import Mathlib.RingTheory.Polynomial.UniqueFactorization

set_option autoImplicit false
set_option maxHeartbeats 800000
set_option synthInstance.maxHeartbeats 100000

namespace CollisionIdeals

open AlgebraicGeometry CategoryTheory MvPolynomial

noncomputable section

/-- The affine coordinate ring `ℂ[P,Q]` inside `ℂ[x,y]`. -/
def planarImageAlgebra (F : Fin 2 → PlanePolynomial) :
    Subalgebra ℂ PlanePolynomial :=
  (coordinateAlgHom F).range

/-- The image algebra is exactly the algebra generated by `P` and `Q`. -/
theorem planarImageAlgebra_eq_adjoin
    (F : Fin 2 → PlanePolynomial) :
    planarImageAlgebra F = Algebra.adjoin ℂ (Set.range F) := by
  simpa [planarImageAlgebra, coordinateAlgHom] using
    (Algebra.adjoin_range_eq_range_aeval ℂ (f := F)).symm

/--
If the coordinate map is injective, the abstract target polynomial ring is
canonically isomorphic to its image `ℂ[P,Q]`.
-/
noncomputable def planarTargetEquivImage
    (F : Fin 2 → PlanePolynomial)
    (hF : Function.Injective (coordinateAlgHom F)) :
    PlanePolynomial ≃ₐ[ℂ] planarImageAlgebra F :=
  AlgEquiv.ofBijective
    (coordinateAlgHom F).rangeRestrict
    ⟨(fun _ _ hxy => hF (congrArg Subtype.val hxy)),
      (coordinateAlgHom F).rangeRestrict_surjective⟩

/--
Under injectivity of the coordinate homomorphism, the image base
`Spec ℂ[P,Q]` is isomorphic to the original abstract affine-plane target.
-/
noncomputable def planarImageBaseIsoTarget
    (F : Fin 2 → PlanePolynomial)
    (hF : Function.Injective (coordinateAlgHom F)) :
    Spec (.of (planarImageAlgebra F)) ≅
      Spec (.of PlanePolynomial) :=
  Scheme.Spec.mapIso
    (planarTargetEquivImage F hF).toRingEquiv.toCommRingCatIso.op

/-- The function field `L = ℂ(x,y)`. -/
abbrev PlaneFunctionField :=
  FractionRing PlanePolynomial

/-- The function field `K = ℂ(P,Q)`. -/
abbrev PlanarBaseFunctionField
    (F : Fin 2 → PlanePolynomial) :=
  FractionRing (planarImageAlgebra F)

/-- The inclusion `ℂ[P,Q] ↪ ℂ(x,y)`. -/
def planarImageAlgebraToFunctionField
    (F : Fin 2 → PlanePolynomial) :
    planarImageAlgebra F →+* PlaneFunctionField :=
  (algebraMap PlanePolynomial PlaneFunctionField).comp
    (algebraMap (planarImageAlgebra F) PlanePolynomial)

theorem planarImageAlgebraToFunctionField_injective
    (F : Fin 2 → PlanePolynomial) :
    Function.Injective (planarImageAlgebraToFunctionField F) :=
  (FaithfulSMul.algebraMap_injective
      PlanePolynomial PlaneFunctionField).comp
    (FaithfulSMul.algebraMap_injective
      (planarImageAlgebra F) PlanePolynomial)

/-- The induced field embedding `K = ℂ(P,Q) ↪ L = ℂ(x,y)`. -/
noncomputable def planarBaseFunctionFieldEmbedding
    (F : Fin 2 → PlanePolynomial) :
    PlanarBaseFunctionField F →+* PlaneFunctionField :=
  IsFractionRing.lift
    (planarImageAlgebraToFunctionField_injective F)

/-- The `K`-algebra structure on `L` induced by `P,Q`. -/
noncomputable def planarBaseFunctionFieldAlgebra
    (F : Fin 2 → PlanePolynomial) :
    Algebra (PlanarBaseFunctionField F) PlaneFunctionField :=
  (planarBaseFunctionFieldEmbedding F).toAlgebra

noncomputable instance
    (F : Fin 2 → PlanePolynomial) :
    Algebra (PlanarBaseFunctionField F) PlaneFunctionField :=
  planarBaseFunctionFieldAlgebra F

noncomputable instance
    (F : Fin 2 → PlanePolynomial) :
    IsScalarTower
      (planarImageAlgebra F)
      (PlanarBaseFunctionField F)
      PlaneFunctionField :=
  IsScalarTower.of_algebraMap_eq fun b => by
    exact
      (IsFractionRing.lift_algebraMap
        (planarImageAlgebraToFunctionField_injective F) b).symm

/--
Data exhibiting `N` as a finite normal closure of
`L = ℂ(x,y)` over `K = ℂ(P,Q)`.

The distinguished embedding remembers the original marked sheet inside
the normal closure.
-/
structure PlanarNormalClosureData
    (F : Fin 2 → PlanePolynomial)
    (N : Type) [Field N]
    [Algebra (PlanarBaseFunctionField F) N] where
  embedding :
    PlaneFunctionField →ₐ[PlanarBaseFunctionField F] N
  normalClosure :
    IsNormalClosure
      (PlanarBaseFunctionField F) PlaneFunctionField N
  finiteIntermediate :
    FiniteDimensional
      (PlanarBaseFunctionField F) PlaneFunctionField
  finiteNormal :
    FiniteDimensional (PlanarBaseFunctionField F) N

namespace PlanarNormalClosureData

variable {F : Fin 2 → PlanePolynomial}
variable {N : Type} [Field N]
variable [Algebra (PlanarBaseFunctionField F) N]

/-- A supplied normal closure is normal over `K`. -/
theorem normal
    (D : PlanarNormalClosureData F N) :
    Normal (PlanarBaseFunctionField F) N := by
  letI : IsNormalClosure
      (PlanarBaseFunctionField F) PlaneFunctionField N :=
    D.normalClosure
  exact
    IsNormalClosure.normal
      (F := PlanarBaseFunctionField F)
      (K := PlaneFunctionField)
      (L := N)

/-- The distinguished copy of `L` inside `N`. -/
def intermediateField
    (D : PlanarNormalClosureData F N) :
    IntermediateField (PlanarBaseFunctionField F) N :=
  D.embedding.fieldRange

/-- The Galois group of the normal-closure model. -/
abbrev galoisGroup
    (_D : PlanarNormalClosureData F N) :=
  N ≃ₐ[PlanarBaseFunctionField F] N

/-- The subgroup fixing the distinguished intermediate field `L`. -/
def intermediateFixingSubgroup
    (D : PlanarNormalClosureData F N) :
    Subgroup D.galoisGroup :=
  D.intermediateField.fixingSubgroup

/-- The Galois group of the supplied finite normal closure is finite. -/
theorem finiteGaloisGroup
    (D : PlanarNormalClosureData F N) :
    Finite D.galoisGroup := by
  letI :
      FiniteDimensional (PlanarBaseFunctionField F) N :=
    D.finiteNormal
  infer_instance

/--
The fixed field of `H` is exactly the distinguished embedded copy of
`L = ℂ(x,y)` in `N`.

This is the field-theoretic content of the notation `H = Gal(N/L)`.
-/
theorem fixedField_intermediateFixingSubgroup
    (D : PlanarNormalClosureData F N) :
    IntermediateField.fixedField
        D.intermediateFixingSubgroup =
      D.intermediateField := by
  letI :
      FiniteDimensional (PlanarBaseFunctionField F) N :=
    D.finiteNormal
  letI :
      Normal (PlanarBaseFunctionField F) N :=
    D.normal
  letI :
      IsGalois (PlanarBaseFunctionField F) N :=
    IsGalois.mk
  exact
    IsGalois.fixedField_fixingSubgroup D.intermediateField

/--
Because `N` is the actual normal closure of the distinguished copy of
`L`, the action of `Gal(N/K)` on its conjugate sheets is faithful.
Equivalently, `H = Gal(N/L)` is core-free.
-/
theorem intermediateFixingSubgroup_normalCore_eq_bot
    (D : PlanarNormalClosureData F N) :
    D.intermediateFixingSubgroup.normalCore = ⊥ := by
  let K := PlanarBaseFunctionField F
  let L := PlaneFunctionField
  letI : FiniteDimensional K L :=
    D.finiteIntermediate
  letI : FiniteDimensional K N :=
    D.finiteNormal
  letI : Normal K N :=
    D.normal
  letI : Algebra L N :=
    D.embedding.toRingHom.toAlgebra
  letI : IsScalarTower K L N :=
    IsScalarTower.of_algebraMap_eq fun x =>
      (D.embedding.commutes x).symm
  let C := D.intermediateFixingSubgroup.normalCore
  have hNormalClosure :
      IntermediateField.normalClosure K L N = ⊤ := by
    letI : IsNormalClosure K L N :=
      D.normalClosure
    exact
      (Algebra.IsAlgebraic.isNormalClosure_iff
        (F := K) (K := L) (L := N)).mp inferInstance |>.2
  have hle :
      IntermediateField.normalClosure K L N ≤
        IntermediateField.fixedField C := by
    rw [normalClosure_le_iff]
    intro f
    intro y hy
    rw [IntermediateField.mem_fixedField_iff]
    intro σ hσ
    obtain ⟨x, rfl⟩ := hy
    let g : N ≃ₐ[K] N :=
      AlgEquiv.ofBijective
        (f.liftNormal N)
        (Algebra.IsAlgebraic.algHom_bijective
          (f.liftNormal N))
    have hconj :
        g⁻¹ * σ * (g⁻¹)⁻¹ ∈
          D.intermediateFixingSubgroup := by
      exact hσ g⁻¹
    have hfix :
        (g⁻¹ * σ * (g⁻¹)⁻¹) (D.embedding x) =
          D.embedding x := by
      exact
        (IntermediateField.mem_fixingSubgroup_iff
          D.intermediateField
          (g⁻¹ * σ * (g⁻¹)⁻¹)).mp hconj
          (D.embedding x) ⟨x, rfl⟩
    have hfix' := congrArg g hfix
    change
      g (g.symm (σ (g (D.embedding x)))) =
        g (D.embedding x) at hfix'
    have hfix'' :
        σ (g (D.embedding x)) =
          g (D.embedding x) := by
      simpa only [AlgEquiv.apply_symm_apply] using hfix'
    have hg :
        g (D.embedding x) = f x := by
      change
        (f.liftNormal N) (algebraMap L N x) =
          f x
      exact f.liftNormal_commutes N x
    change σ (f x) = f x
    simpa only [hg] using hfix''
  have hfixed :
      IntermediateField.fixedField C = ⊤ := by
    apply top_unique
    rw [← hNormalClosure]
    exact hle
  have hcorrespondence :
      (IntermediateField.fixedField C).fixingSubgroup = C :=
    IntermediateField.fixingSubgroup_fixedField C
  rw [hfixed] at hcorrespondence
  change C = ⊥
  simpa using hcorrespondence.symm

end PlanarNormalClosureData

/--
The canonical function-field extension `K = ℂ(P,Q) ⊂ L = ℂ(x,y)` is
trivial.

Because `planarBaseFunctionFieldEmbedding F` is always injective, surjectivity
is the type-correct formulation of `K = L`.
-/
def PlanarFunctionFieldExtensionTrivial
    (F : Fin 2 → PlanePolynomial) : Prop :=
  Function.Surjective (planarBaseFunctionFieldEmbedding F)

/--
Triviality of `K ⊂ L` gives generic degree one.
-/
theorem planarFunctionField_finrank_eq_one
    (F : Fin 2 → PlanePolynomial)
    (hTrivial : PlanarFunctionFieldExtensionTrivial F) :
    Module.finrank
      (PlanarBaseFunctionField F) PlaneFunctionField = 1 := by
  apply finrank_eq_one (1 : PlaneFunctionField) one_ne_zero
  intro z
  obtain ⟨c, hc⟩ := hTrivial z
  exact ⟨c, by simpa [Algebra.smul_def] using hc⟩

/-- The finite-completion coordinate ring: the integral closure of `ℂ[P,Q]` in `ℂ(x,y)`. -/
abbrev PlanarFiniteCompletionRing
    (F : Fin 2 → PlanePolynomial) :=
  normalizedCoordinateRing (planarImageAlgebra F) PlaneFunctionField

/-- The normalized intermediate affine model `X̄ = Norm_L(Y)`. -/
def planarFiniteCompletion
    (F : Fin 2 → PlanePolynomial) : Scheme :=
  normalizedAffineModel (planarImageAlgebra F) PlaneFunctionField

/-- The canonical morphism `X̄ ⟶ Y = Spec ℂ[P,Q]`. -/
def planarFiniteCompletionToBase
    (F : Fin 2 → PlanePolynomial) :
    planarFiniteCompletion F ⟶ Spec (.of (planarImageAlgebra F)) :=
  normalizedModelToBase (planarImageAlgebra F) PlaneFunctionField

/-- The original affine-plane sheet mapped to `Y = Spec ℂ[P,Q]`. -/
def planarSourceToImageBase
    (F : Fin 2 → PlanePolynomial) :
    Spec (.of PlanePolynomial) ⟶
      Spec (.of (planarImageAlgebra F)) :=
  Spec.map
    (CommRingCat.ofHom
      (algebraMap (planarImageAlgebra F) PlanePolynomial))

/--
The canonical intermediate morphism
`X = Spec ℂ[x,y] ⟶ X̄`.

Its being an open immersion is the Zariski-main input, stated separately
below rather than built into the definition.
-/
def planarSourceToFiniteCompletion
    (F : Fin 2 → PlanePolynomial) :
    Spec (.of PlanePolynomial) ⟶ planarFiniteCompletion F :=
  intermediateToNormalization
    (B := planarImageAlgebra F)
    (E := PlaneFunctionField)
    (A := PlanePolynomial)

/-- The candidate intermediate model lies over the original map to `Spec ℂ[P,Q]`. -/
theorem planarSourceToFiniteCompletion_comp_toBase
    (F : Fin 2 → PlanePolynomial) :
    planarSourceToFiniteCompletion F ≫ planarFiniteCompletionToBase F =
      planarSourceToImageBase F :=
  intermediateToNormalization_comp_toBase
    (B := planarImageAlgebra F)
    (E := PlaneFunctionField)
    (A := PlanePolynomial)

/-- The explicit Zariski-main assertion for the planar intermediate model. -/
def IsPlanarIntermediateOpen
    (F : Fin 2 → PlanePolynomial) : Prop :=
  IsOpenImmersion (planarSourceToFiniteCompletion F)

/-- The deleted boundary `X̄ ∖ X` of the intermediate affine-plane model. -/
def planarFiniteCompletionBoundary
    (F : Fin 2 → PlanePolynomial) :
    Set (planarFiniteCompletion F) :=
  (Set.range (planarSourceToFiniteCompletion F).base)ᶜ

/-- Finiteness of the integral closure defining `X̄`. -/
def IsPlanarFiniteCompletion
    (F : Fin 2 → PlanePolynomial) : Prop :=
  Module.Finite
    (planarImageAlgebra F)
    (PlanarFiniteCompletionRing F)

/--
The remaining normalization-form planar rigidity statement.

For a planar Keller map, the normalized finite model
`X = Spec ℂ[x,y] ⟶ X̄ ⟶ Y` cannot have a nontrivial function-field
extension when the affine-plane sheet is the indicated open submodel.

This is a theorem target, not a consequence of the normalization
construction.  Proving it is the hidden-ramification step of the planar
Jacobian problem.
-/
def PlanarNormalizationRigidity : Prop :=
  ∀ (F : Fin 2 → PlanePolynomial),
    IsPlanarKeller F →
      IsPlanarFiniteCompletion F →
        IsPlanarIntermediateOpen F →
          PlanarFunctionFieldExtensionTrivial F

/--
A nontrivial finite-completion configuration of the precise kind excluded
by `PlanarNormalizationRigidity`.
-/
def HasNontrivialPlanarFiniteModel
    (F : Fin 2 → PlanePolynomial) : Prop :=
  IsPlanarKeller F ∧
    IsPlanarFiniteCompletion F ∧
      IsPlanarIntermediateOpen F ∧
        ¬ PlanarFunctionFieldExtensionTrivial F

/--
Normalization rigidity is formally equivalent to the nonexistence of a
nontrivial planar finite model.
-/
theorem planarNormalizationRigidity_iff_no_nontrivial_model :
    PlanarNormalizationRigidity ↔
      ∀ (F : Fin 2 → PlanePolynomial),
        ¬ HasNontrivialPlanarFiniteModel F := by
  constructor
  · intro hRigidity F hModel
    exact
      hModel.2.2.2
        (hRigidity F hModel.1 hModel.2.1 hModel.2.2.1)
  · intro hNoModel F hKeller hFinite hOpen
    by_contra hNontrivial
    exact
      hNoModel F
        ⟨hKeller, hFinite, hOpen, hNontrivial⟩

section NormalClosureNormalization

variable {F : Fin 2 → PlanePolynomial}
variable {N : Type} [Field N]
variable [Algebra (PlanarBaseFunctionField F) N]

/--
The `ℂ[P,Q]`-algebra structure on `N`, obtained through
`ℂ[P,Q] ⊂ K = ℂ(P,Q) ⊂ N`.

It remains explicit to avoid creating a typeclass diamond with the canonical
fraction-field algebra structure when `N = K`.
-/
noncomputable def planarNormalClosureBaseAlgebra :
    Algebra (planarImageAlgebra F) N :=
  ((algebraMap (PlanarBaseFunctionField F) N).comp
    (algebraMap (planarImageAlgebra F)
      (PlanarBaseFunctionField F))).toAlgebra

/--
The marked embedding `L ↪ N`, regarded as an algebra homomorphism over the
affine coordinate ring `ℂ[P,Q]`.
-/
noncomputable def planarNormalClosureEmbeddingOverBase
    (D : PlanarNormalClosureData F N) :
    letI : Algebra (planarImageAlgebra F) N :=
      planarNormalClosureBaseAlgebra (F := F) (N := N)
    PlaneFunctionField →ₐ[planarImageAlgebra F] N := by
  letI : Algebra (planarImageAlgebra F) N :=
    planarNormalClosureBaseAlgebra (F := F) (N := N)
  exact
    { D.embedding.toRingHom with
      commutes' := fun b => by
        rw [IsScalarTower.algebraMap_apply
          (planarImageAlgebra F)
          (PlanarBaseFunctionField F)
          PlaneFunctionField]
        exact D.embedding.commutes
          (algebraMap (planarImageAlgebra F)
            (PlanarBaseFunctionField F) b) }

/--
The integral closure of `ℂ[P,Q]` in an ambient field `N`.

When `N` is supplied by `PlanarNormalClosureData`, this is the coordinate
ring of the normal-closure model.  The definition itself only needs the
displayed field extension.
-/
abbrev PlanarNormalizationInExtensionRing :=
  @normalizedCoordinateRing
    (planarImageAlgebra F) N
    inferInstance inferInstance
    (planarNormalClosureBaseAlgebra (F := F) (N := N))

/--
The relative integral-closure model of `Y = Spec ℂ[P,Q]` inside `N`.

For `N` furnished by `PlanarNormalClosureData`, this is the model denoted
`Z = Norm_N(Y)`.  Finiteness and the Galois hypotheses are deliberately
kept in the accompanying cover data rather than asserted by this definition.
-/
def planarNormalizationInExtension : Scheme :=
  letI : Algebra (planarImageAlgebra F) N :=
    planarNormalClosureBaseAlgebra (F := F) (N := N)
  normalizedAffineModel (planarImageAlgebra F) N

/-- The canonical morphism `Z ⟶ Y`. -/
def planarNormalizationInExtensionToBase :
    planarNormalizationInExtension (F := F) (N := N) ⟶
      Spec (.of (planarImageAlgebra F)) :=
  letI : Algebra (planarImageAlgebra F) N :=
    planarNormalClosureBaseAlgebra (F := F) (N := N)
  normalizedModelToBase (planarImageAlgebra F) N

/-- The inclusion of normalization rings induced by the marked embedding `L ↪ N`. -/
def planarNormalizationRingMap
    (D : PlanarNormalClosureData F N) :
    PlanarFiniteCompletionRing F →ₐ[planarImageAlgebra F]
      PlanarNormalizationInExtensionRing (F := F) (N := N) := by
  letI : Algebra (planarImageAlgebra F) N :=
    planarNormalClosureBaseAlgebra (F := F) (N := N)
  exact
    normalizationMap N
      (planarNormalClosureEmbeddingOverBase D)

/--
The Galois normalization dominates the marked intermediate normalization:
`Z ⟶ X̄`.
-/
def planarNormalClosureModelToFiniteCompletion
    (D : PlanarNormalClosureData F N) :
    planarNormalizationInExtension (F := F) (N := N) ⟶
      planarFiniteCompletion F :=
  Spec.map
    (CommRingCat.ofHom
      (planarNormalizationRingMap D).toRingHom)

/-- The triangle `Z ⟶ X̄ ⟶ Y` agrees with the normalization map `Z ⟶ Y`. -/
theorem planarNormalClosureModelToFiniteCompletion_comp_toBase
    (D : PlanarNormalClosureData F N) :
    planarNormalClosureModelToFiniteCompletion D ≫
        planarFiniteCompletionToBase F =
      planarNormalizationInExtensionToBase (F := F) (N := N) := by
  letI : Algebra (planarImageAlgebra F) N :=
    planarNormalClosureBaseAlgebra (F := F) (N := N)
  exact
    normalizationDomination_comp_toBase N
      (planarNormalClosureEmbeddingOverBase D)

/--
Finiteness of the integral closure of `ℂ[P,Q]` in `N`.

For `N` supplied by normal-closure data, this is finiteness of the model `Z`.
-/
def IsPlanarFiniteNormalizationInExtension : Prop :=
  Module.Finite
    (planarImageAlgebra F)
    (PlanarNormalizationInExtensionRing (F := F) (N := N))

end NormalClosureNormalization

end

end CollisionIdeals
