import CollisionIdeals.Basic
import Mathlib.RingTheory.Ideal.Colon
import Mathlib.RingTheory.Ideal.Quotient.Operations

set_option autoImplicit false
set_option maxHeartbeats 800000

namespace CollisionIdeals

noncomputable section

universe u

variable {A : Type u} [CommRing A]

/-- The residual ideal left after removing `J` from `V(I)`. -/
def offDiagonalColonIdeal (I J : Ideal A) : Ideal A :=
  I.colon J

/--
The usual ideal saturation `I : J^∞`, indexed by strictly positive
powers of `J`.
-/
def idealSaturation (I J : Ideal A) : Ideal A :=
  ⨆ n : ℕ, I.colon (J ^ (n + 1))

/--
The pullback of the annihilator of `J/I` is the colon ideal `I : J`.
-/
theorem comap_annihilator_map_quotient_eq_colon
    (I J : Ideal A) :
    ((J.map (Ideal.Quotient.mk I)).annihilator).comap
        (Ideal.Quotient.mk I) =
      I.colon J := by
  ext x
  constructor
  · intro hx
    rw [Submodule.mem_colon]
    intro j hj
    have hzero :
        Ideal.Quotient.mk I x *
            Ideal.Quotient.mk I j = 0 := by
      exact
        Submodule.mem_annihilator.mp hx _
          (Ideal.mem_map_of_mem (Ideal.Quotient.mk I) hj)
    rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem] at hzero
    exact hzero
  · intro hx
    apply Submodule.mem_annihilator.mpr
    intro z hz
    obtain ⟨j, hj, rfl⟩ :=
      (Ideal.mem_map_iff_of_surjective
        (Ideal.Quotient.mk I)
        Ideal.Quotient.mk_surjective).mp hz
    change
      Ideal.Quotient.mk I x *
          Ideal.Quotient.mk I j = 0
    rw [← map_mul, Ideal.Quotient.eq_zero_iff_mem]
    exact Submodule.mem_colon.mp hx j hj

/-- The annihilator of an idempotent summand is its complementary summand. -/
theorem annihilator_span_idempotent
    {q : A} (hq : IsIdempotentElem q) :
    (Ideal.span {q}).annihilator =
      Ideal.span {1 - q} := by
  apply le_antisymm
  · intro x hx
    rw [Ideal.mem_span_singleton']
    refine ⟨x, ?_⟩
    have hxq : x * q = 0 :=
      Submodule.mem_annihilator.mp hx q
        (Ideal.mem_span_singleton_self q)
    rw [mul_sub, mul_one, hxq, sub_zero]
  · intro x hx
    rw [Ideal.mem_span_singleton'] at hx
    obtain ⟨a, rfl⟩ := hx
    apply Submodule.mem_annihilator.mpr
    intro y hy
    rw [Ideal.mem_span_singleton'] at hy
    obtain ⟨b, rfl⟩ := hy
    change (a * (1 - q)) * (b * q) = 0
    rw [show (a * (1 - q)) * (b * q) =
      (a * b) * ((1 - q) * q) by ring]
    rw [sub_mul, one_mul, hq.eq, sub_self, mul_zero]

theorem span_idempotent_inf_span_one_sub
    {q : A} (hq : IsIdempotentElem q) :
    Ideal.span {q} ⊓ Ideal.span {1 - q} = ⊥ := by
  rw [← annihilator_span_idempotent hq]
  apply le_bot_iff.mp
  intro x hx
  have hxq : x * q = 0 :=
    Submodule.mem_annihilator.mp hx.2 q
      (Ideal.mem_span_singleton_self q)
  obtain ⟨a, rfl⟩ :=
    Ideal.mem_span_singleton'.mp hx.1
  rw [Ideal.mem_bot]
  simpa [mul_assoc, hq.eq] using hxq

theorem span_idempotent_sup_span_one_sub
    (q : A) :
    Ideal.span {q} ⊔ Ideal.span {1 - q} = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  have hq : q ∈ Ideal.span {q} ⊔ Ideal.span {1 - q} :=
    le_sup_left (a := Ideal.span {q})
      (b := Ideal.span {1 - q})
      (Ideal.mem_span_singleton_self q)
  have ht : 1 - q ∈ Ideal.span {q} ⊔ Ideal.span {1 - q} :=
    le_sup_right (a := Ideal.span {q})
      (b := Ideal.span {1 - q})
      (Ideal.mem_span_singleton_self (1 - q))
  have := (Ideal.span {q} ⊔ Ideal.span {1 - q}).add_mem hq ht
  simpa using this

/--
The image of `J` modulo `I` is generated by an idempotent.  This is the
algebraic form of `V(J/I)` being open and closed in `Spec(A/I)`.
-/
def IsClopenModulo
    (I J : Ideal A) (projector : A ⧸ I) : Prop :=
  I ≤ J ∧
  IsIdempotentElem projector ∧
    J.map (Ideal.Quotient.mk I) =
      Ideal.span {projector}

/-- For a clopen summand, every positive colon power equals the first one. -/
theorem colon_power_eq_colon_of_isClopenModulo
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q)
    (n : ℕ) :
    I.colon (J ^ (n + 1)) = I.colon J := by
  rw [← comap_annihilator_map_quotient_eq_colon I (J ^ (n + 1)),
    Ideal.map_pow, h.2.2, Ideal.span_singleton_pow,
    h.2.1.pow_eq (Nat.succ_ne_zero n),
    ← h.2.2,
    comap_annihilator_map_quotient_eq_colon I J]

/-- Clopenness makes the infinite saturation stabilize at the first colon. -/
theorem idealSaturation_eq_offDiagonalColonIdeal
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    idealSaturation I J = offDiagonalColonIdeal I J := by
  simp only [idealSaturation,
    colon_power_eq_colon_of_isClopenModulo I J q h,
    iSup_const, offDiagonalColonIdeal]

/-- The residual colon ideal is the pullback of the complementary projector. -/
theorem offDiagonalColonIdeal_eq_comap_complement
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    offDiagonalColonIdeal I J =
      (Ideal.span {1 - q}).comap
        (Ideal.Quotient.mk I) := by
  rw [offDiagonalColonIdeal,
    ← comap_annihilator_map_quotient_eq_colon I J,
    h.2.2,
    annihilator_span_idempotent h.2.1]

/-- A clopen ideal and its residual complement intersect in the base ideal. -/
theorem inf_offDiagonalColonIdeal_eq
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    J ⊓ offDiagonalColonIdeal I J = I := by
  let π := Ideal.Quotient.mk I
  have hJ :
      (Ideal.span {q}).comap π = J := by
    rw [← h.2.2,
      Ideal.comap_map_of_surjective
        π Ideal.Quotient.mk_surjective J]
    change J ⊔ RingHom.ker π = J
    apply sup_eq_left.mpr
    simpa [π, Ideal.mk_ker] using h.1
  rw [offDiagonalColonIdeal_eq_comap_complement I J q h,
    ← hJ, ← Ideal.comap_inf,
    span_idempotent_inf_span_one_sub h.2.1,
    ← RingHom.ker_eq_comap_bot, Ideal.mk_ker]

/-- A clopen ideal and its residual complement are comaximal. -/
theorem sup_offDiagonalColonIdeal_eq_top
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    J ⊔ offDiagonalColonIdeal I J = ⊤ := by
  let π := Ideal.Quotient.mk I
  have hker :
      RingHom.ker π ≤ J ⊔ offDiagonalColonIdeal I J := by
    rw [Ideal.mk_ker]
    exact h.1.trans le_sup_left
  calc
    J ⊔ offDiagonalColonIdeal I J =
        ((J ⊔ offDiagonalColonIdeal I J).map π).comap π := by
          rw [Ideal.comap_map_of_surjective
              π Ideal.Quotient.mk_surjective]
          change
            J ⊔ offDiagonalColonIdeal I J =
              (J ⊔ offDiagonalColonIdeal I J) ⊔
                RingHom.ker π
          exact (sup_eq_left.mpr hker).symm
    _ = (Ideal.span {q} ⊔
          Ideal.span {1 - q}).comap π := by
          rw [Ideal.map_sup, h.2.2,
            offDiagonalColonIdeal_eq_comap_complement I J q h,
            Ideal.map_comap_of_surjective
              π Ideal.Quotient.mk_surjective]
    _ = ⊤ := by
          rw [span_idempotent_sup_span_one_sub,
            Ideal.comap_top]

/--
There is a single element equal to `1` along `V(J)` that annihilates `J`
modulo `I`.  Localizing at this element makes `I` and `J` equal.
-/
theorem exists_neighborhood_element_of_isClopenModulo
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    ∃ s : A,
      s - 1 ∈ J ∧
        ∀ j ∈ J, s * j ∈ I := by
  let π := Ideal.Quotient.mk I
  have hqmap :
      q ∈ J.map π := by
    rw [h.2.2]
    exact Ideal.mem_span_singleton_self q
  obtain ⟨j, hj, hjq⟩ :=
    (Ideal.mem_map_iff_of_surjective
      π Ideal.Quotient.mk_surjective).mp hqmap
  refine ⟨1 - j, ?_, ?_⟩
  · simpa [sub_eq_add_neg, add_assoc] using J.neg_mem hj
  · intro z hz
    apply
      Submodule.mem_colon.mp
        (show 1 - j ∈ I.colon J from ?_) z hz
    rw [← offDiagonalColonIdeal,
      offDiagonalColonIdeal_eq_comap_complement I J q h]
    change π (1 - j) ∈ Ideal.span {1 - q}
    rw [map_sub, map_one, hjq]
    exact Ideal.mem_span_singleton_self (1 - q)

theorem isCoprime_diagonal_offDiagonalColonIdeal
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    IsCoprime J (offDiagonalColonIdeal I J) := by
  rw [Ideal.isCoprime_iff_sup_eq]
  exact sup_offDiagonalColonIdeal_eq_top I J q h

/-- The Chinese-remainder decomposition associated to a clopen summand. -/
noncomputable def quotientEquivDiagonalProdOffDiagonal
    (I J : Ideal A) (q : A ⧸ I)
    (h : IsClopenModulo I J q) :
    A ⧸ I ≃+*
      (A ⧸ J) × (A ⧸ offDiagonalColonIdeal I J) := by
  let e :=
    Ideal.quotientInfEquivQuotientProd
      J (offDiagonalColonIdeal I J)
      (isCoprime_diagonal_offDiagonalColonIdeal I J q h)
  exact
    (Ideal.quotEquivOfEq
      (inf_offDiagonalColonIdeal_eq I J q h).symm).trans e

section Collision

universe v w

variable {R : Type u} [CommRing R]
variable {ι : Type v} {κ : Type w}

/--
The ideal of the off-diagonal collision summand.  Once the diagonal is
clopen, saturation by `I_Δ` stabilizes at this first colon ideal.
-/
def collisionOffDiagonalIdeal
    (F : κ → SourceRing R ι) :
    Ideal (PairRing R ι) :=
  offDiagonalColonIdeal
    (relationIdeal F)
    (diagonalIdeal (R := R) (ι := ι))

/-- The conventional saturation `I_R(F) : I_Δ^∞`. -/
def collisionIdealSaturation
    (F : κ → SourceRing R ι) :
    Ideal (PairRing R ι) :=
  idealSaturation
    (relationIdeal F)
    (diagonalIdeal (R := R) (ι := ι))

/--
An explicit off-diagonal projector for the collision ring.  This is the
algebraic datum supplied by the diagonal being open and closed.
-/
def IsCollisionOffDiagonalProjector
    (F : κ → SourceRing R ι)
    (q : CollisionRing F) : Prop :=
  IsIdempotentElem q ∧
    obstructionIdeal F = Ideal.span {q}

theorem isClopenModulo_of_collisionOffDiagonalProjector
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    IsClopenModulo
      (relationIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q := by
  refine ⟨relationIdeal_le_diagonalIdeal F, hq.1, ?_⟩
  exact hq.2

/-- For a clopen collision diagonal, `I_R : I_Δ^∞ = I_R : I_Δ`. -/
theorem collisionIdealSaturation_eq_offDiagonalIdeal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    collisionIdealSaturation F =
      collisionOffDiagonalIdeal F := by
  exact
    idealSaturation_eq_offDiagonalColonIdeal
      (relationIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

theorem relationIdeal_eq_diagonal_inf_offDiagonal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    relationIdeal F =
      diagonalIdeal (R := R) (ι := ι) ⊓
        collisionOffDiagonalIdeal F := by
  exact
    (inf_offDiagonalColonIdeal_eq
      (relationIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)).symm

theorem diagonal_sup_collisionOffDiagonalIdeal_eq_top
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    diagonalIdeal (R := R) (ι := ι) ⊔
      collisionOffDiagonalIdeal F = ⊤ := by
  exact
    sup_offDiagonalColonIdeal_eq_top
      (relationIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

/--
There is an `h ≡ 1 mod I_Δ` with `h I_Δ ⊆ I_R`; hence `I_R` and
`I_Δ` agree on the principal neighborhood selected by `h`.
-/
theorem exists_collision_diagonal_neighborhood_element
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    ∃ h : PairRing R ι,
      h - 1 ∈ diagonalIdeal (R := R) (ι := ι) ∧
        ∀ z ∈ diagonalIdeal (R := R) (ι := ι),
          h * z ∈ relationIdeal F := by
  exact
    exists_neighborhood_element_of_isClopenModulo
      (relationIdeal F)
      (diagonalIdeal (R := R) (ι := ι))
      q
      (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

/-- The collision ring splits into its diagonal and off-diagonal factors. -/
noncomputable def collisionRingEquivDiagonalProdOffDiagonal
    (F : κ → SourceRing R ι)
    (q : CollisionRing F)
    (hq : IsCollisionOffDiagonalProjector F q) :
    CollisionRing F ≃+*
      (PairRing R ι ⧸ diagonalIdeal (R := R) (ι := ι)) ×
      (PairRing R ι ⧸ collisionOffDiagonalIdeal F) :=
  quotientEquivDiagonalProdOffDiagonal
    (relationIdeal F)
    (diagonalIdeal (R := R) (ι := ι))
    q
    (isClopenModulo_of_collisionOffDiagonalProjector F q hq)

/-- The obstruction vanishes exactly when the off-diagonal ideal is the unit ideal. -/
theorem obstructionIdeal_eq_bot_iff_collisionOffDiagonalIdeal_eq_top
    (F : κ → SourceRing R ι) :
    obstructionIdeal F = ⊥ ↔
      collisionOffDiagonalIdeal F = ⊤ := by
  rw [obstructionIdeal_eq_bot_iff]
  constructor
  · intro h
    rw [collisionOffDiagonalIdeal, offDiagonalColonIdeal,
      h, Ideal.eq_top_iff_one]
    apply Submodule.mem_colon.mpr
    intro x hx
    simpa using hx
  · intro h
    apply le_antisymm (relationIdeal_le_diagonalIdeal F)
    intro x hx
    rw [collisionOffDiagonalIdeal, offDiagonalColonIdeal,
      Ideal.eq_top_iff_one] at h
    have hx' := Submodule.mem_colon.mp h x hx
    simpa using hx'

/-- Equivalently, the off-diagonal quotient ring is the zero ring. -/
theorem obstructionIdeal_eq_bot_iff_offDiagonalFactor_subsingleton
    (F : κ → SourceRing R ι) :
    obstructionIdeal F = ⊥ ↔
      Subsingleton
        (PairRing R ι ⧸ collisionOffDiagonalIdeal F) := by
  rw [Ideal.Quotient.subsingleton_iff]
  exact
    obstructionIdeal_eq_bot_iff_collisionOffDiagonalIdeal_eq_top
      F

end Collision

end

end CollisionIdeals
