import CollisionIdeals.DiagonalKernel
import CollisionIdeals.OffDiagonal
import CollisionIdeals.Planar
import CollisionIdeals.Secant

set_option autoImplicit false
set_option maxHeartbeats 800000

namespace CollisionIdeals

open MvPolynomial

noncomputable section

universe u

variable {R : Type u} [CommRing R]

/--
If `δ` annihilates `J / I` and is congruent modulo `J` to a unit, then
the colon ideal `I : J` is generated by `I` and `δ`.
-/
theorem colon_eq_sup_span_singleton_of_secant
    {A : Type u} [CommRing A]
    (I J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ z ∈ J, δ * z ∈ I)
    (hmod : δ - (c : A) ∈ J) :
    I.colon J = I ⊔ Ideal.span {δ} := by
  apply le_antisymm
  · intro x hx
    let K := I ⊔ Ideal.span {δ}
    have hxmod : x * (δ - (c : A)) ∈ I :=
      Submodule.mem_colon.mp hx _ hmod
    have hxdelta : x * δ ∈ Ideal.span ({δ} : Set A) := by
      rw [Ideal.mem_span_singleton']
      exact ⟨x, rfl⟩
    have hxc : x * (c : A) ∈ K := by
      have hsub :=
        K.sub_mem
          (show x * δ ∈ K from Ideal.mem_sup_right hxdelta)
          (show x * (δ - (c : A)) ∈ K from Ideal.mem_sup_left hxmod)
      convert hsub using 1
      ring
    have hinv := K.mul_mem_left (↑(c⁻¹) : A) hxc
    simpa [K, mul_assoc] using hinv
  · intro x hx
    obtain ⟨i, hi, d, hd, hid⟩ :=
      Submodule.mem_sup.mp hx
    rw [Ideal.mem_span_singleton'] at hd
    obtain ⟨a, rfl⟩ := hd
    subst x
    apply Submodule.mem_colon.mpr
    intro z hz
    change (i + a * δ) * z ∈ I
    rw [add_mul, mul_assoc]
    exact I.add_mem
      (I.mul_mem_right z hi)
      (I.mul_mem_left a (hann z hz))

/--
Under `I ≤ J`, the same secant hypotheses identify `I = J` with the
unit-ideal condition `I + (δ) = A`.
-/
theorem ideal_eq_iff_sup_span_singleton_eq_top_of_secant
    {A : Type u} [CommRing A]
    (I J : Ideal A) (δ : A) (c : Aˣ)
    (hIJ : I ≤ J)
    (hann : ∀ z ∈ J, δ * z ∈ I)
    (hmod : δ - (c : A) ∈ J) :
    I = J ↔ I ⊔ Ideal.span {δ} = ⊤ := by
  constructor
  · intro h
    rw [Ideal.eq_top_iff_one]
    let K := I ⊔ Ideal.span {δ}
    have hδ : δ ∈ K :=
      Ideal.mem_sup_right
        (Ideal.mem_span_singleton_self δ)
    have hδc : δ - (c : A) ∈ K :=
      Ideal.mem_sup_left (by simpa [h] using hmod)
    have hc : (c : A) ∈ K := by
      have := K.sub_mem hδ hδc
      convert this using 1
      ring
    have hinv := K.mul_mem_left (↑(c⁻¹) : A) hc
    simpa [K, mul_assoc] using hinv
  · intro htop
    apply le_antisymm hIJ
    intro z hz
    have hone : (1 : A) ∈ I ⊔ Ideal.span {δ} := by
      rw [htop]
      trivial
    obtain ⟨r, hr, d, hd, hrd⟩ :=
      Submodule.mem_sup.mp hone
    rw [Ideal.mem_span_singleton'] at hd
    obtain ⟨a, rfl⟩ := hd
    have hzEq : z = r * z + a * (δ * z) := by
      calc
        z = 1 * z := by rw [one_mul]
        _ = (r + a * δ) * z := by rw [hrd]
        _ = r * z + a * (δ * z) := by ring
    rw [hzEq]
    exact I.add_mem
      (I.mul_mem_right z hr)
      (I.mul_mem_left a (hann z hz))

/-- In two variables, the diagonal ideal is generated by the two coordinate differences. -/
theorem diagonalIdeal_fin_two_eq_span_pair :
    diagonalIdeal (R := R) (ι := Fin 2) =
      Ideal.span
        ({diagonalGenerator (R := R) 0,
          diagonalGenerator (R := R) 1} :
          Set (PairRing R (Fin 2))) := by
  rw [diagonalIdeal]
  congr 1
  ext z
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i <;> simp
  · intro hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl
    · exact Set.mem_range_self 0
    · exact Set.mem_range_self 1

/--
Every planar polynomial has a two-coordinate secant decomposition whose
coefficients restrict on the diagonal to the two formal partial derivatives.
-/
theorem exists_planarSecantCoefficients
    (p : SourceRing R (Fin 2)) :
    ∃ a b : PairRing R (Fin 2),
      leftRename p - rightRename p =
          a * diagonalGenerator (R := R) 0 +
            b * diagonalGenerator (R := R) 1 ∧
      diagonalEval a = pderiv 0 p ∧
      diagonalEval b = pderiv 1 p := by
  induction p using MvPolynomial.induction_on with
  | C r =>
      exact ⟨0, 0, by simp, by simp, by simp⟩
  | add p q hp hq =>
      obtain ⟨ap, bp, hpEq, hpa, hpb⟩ := hp
      obtain ⟨aq, bq, hqEq, hqa, hqb⟩ := hq
      refine ⟨ap + aq, bp + bq, ?_, ?_, ?_⟩
      · rw [map_add, map_add]
        calc
          leftRename p + leftRename q -
              (rightRename p + rightRename q) =
            (leftRename p - rightRename p) +
              (leftRename q - rightRename q) := by ring
          _ = _ := by rw [hpEq, hqEq]; ring
      · simp [hpa, hqa]
      · simp [hpb, hqb]
  | mul_X p i hp =>
      obtain ⟨a, b, hpEq, ha, hb⟩ := hp
      fin_cases i
      · let xr : PairRing R (Fin 2) := X (Sum.inr 0)
        refine ⟨leftRename p + a * xr, b * xr, ?_, ?_, ?_⟩
        · rw [map_mul, map_mul, leftRename_X, rightRename_X]
          change
            leftRename p * X (Sum.inl 0) -
                rightRename p * X (Sum.inr 0) =
              (leftRename p + a * xr) *
                  diagonalGenerator (R := R) 0 +
                (b * xr) * diagonalGenerator (R := R) 1
          rw [show
            leftRename p * X (Sum.inl 0) -
                rightRename p * X (Sum.inr 0) =
              leftRename p * diagonalGenerator (R := R) 0 +
                (leftRename p - rightRename p) * xr by
                  simp [diagonalGenerator, xr]
                  ring,
            hpEq]
          ring
        · rw [map_add, map_mul, diagonalEval_leftRename, ha]
          simp [xr, diagonalEval]
          ring
        · rw [map_mul, hb]
          simp [xr, diagonalEval]
          ring
      · let yr : PairRing R (Fin 2) := X (Sum.inr 1)
        refine ⟨a * yr, leftRename p + b * yr, ?_, ?_, ?_⟩
        · rw [map_mul, map_mul, leftRename_X, rightRename_X]
          change
            leftRename p * X (Sum.inl 1) -
                rightRename p * X (Sum.inr 1) =
              (a * yr) * diagonalGenerator (R := R) 0 +
                (leftRename p + b * yr) *
                  diagonalGenerator (R := R) 1
          rw [show
            leftRename p * X (Sum.inl 1) -
                rightRename p * X (Sum.inr 1) =
              leftRename p * diagonalGenerator (R := R) 1 +
                (leftRename p - rightRename p) * yr by
                  simp [diagonalGenerator, yr]
                  ring,
            hpEq]
          ring
        · rw [map_mul, ha]
          simp [yr, diagonalEval]
          ring
        · rw [map_add, map_mul, diagonalEval_leftRename, hb]
          simp [yr, diagonalEval]
          ring

/-- A secant decomposition of one planar polynomial with its diagonal values. -/
structure PlanarSecantData
    (p : SourceRing R (Fin 2)) where
  first : PairRing R (Fin 2)
  second : PairRing R (Fin 2)
  equation :
    leftRename p - rightRename p =
      first * diagonalGenerator (R := R) 0 +
        second * diagonalGenerator (R := R) 1
  diagonal_first :
    diagonalEval first = pderiv 0 p
  diagonal_second :
    diagonalEval second = pderiv 1 p

/-- Every planar polynomial admits secant data. -/
theorem nonempty_planarSecantData
    (p : SourceRing R (Fin 2)) :
    Nonempty (PlanarSecantData p) := by
  obtain ⟨a, b, hab, ha, hb⟩ :=
    exists_planarSecantCoefficients p
  exact ⟨⟨a, b, hab, ha, hb⟩⟩

/-- Fix a secant decomposition for each planar polynomial. -/
noncomputable def planarSecantData
    (p : SourceRing R (Fin 2)) :
    PlanarSecantData p :=
  Classical.choice (nonempty_planarSecantData p)

/-- The determinant of the chosen planar secant matrix. -/
noncomputable def planarSecantDet
    (F : Fin 2 → SourceRing R (Fin 2)) :
    PairRing R (Fin 2) :=
  secantDet
    (planarSecantData (F 0)).first
    (planarSecantData (F 0)).second
    (planarSecantData (F 1)).first
    (planarSecantData (F 1)).second

/-- The chosen secant determinant restricts to the formal Jacobian determinant. -/
theorem diagonalEval_planarSecantDet
    (F : Fin 2 → SourceRing R (Fin 2)) :
    diagonalEval (planarSecantDet F) =
      pderiv 0 (F 0) * pderiv 1 (F 1) -
        pderiv 1 (F 0) * pderiv 0 (F 1) := by
  simp only [planarSecantDet, secantDet, map_sub, map_mul,
    (planarSecantData (F 0)).diagonal_first,
    (planarSecantData (F 0)).diagonal_second,
    (planarSecantData (F 1)).diagonal_first,
    (planarSecantData (F 1)).diagonal_second]

/-- The chosen planar secant determinant annihilates `I_Δ / I_R`. -/
theorem planarSecantDet_mul_diagonalIdeal_mem_relationIdeal
    (F : Fin 2 → SourceRing R (Fin 2))
    (z : PairRing R (Fin 2))
    (hz : z ∈ diagonalIdeal (R := R) (ι := Fin 2)) :
    planarSecantDet F * z ∈ relationIdeal F := by
  let a := (planarSecantData (F 0)).first
  let b := (planarSecantData (F 0)).second
  let c := (planarSecantData (F 1)).first
  let d := (planarSecantData (F 1)).second
  have hz' :
      z ∈ Ideal.span
        ({diagonalGenerator (R := R) 0,
          diagonalGenerator (R := R) 1} :
          Set (PairRing R (Fin 2))) := by
    rwa [← diagonalIdeal_fin_two_eq_span_pair]
  have hmem :=
    secantDet_mul_diagonalIdeal_mem_relationIdeal
      a b c d
      (diagonalGenerator (R := R) 0)
      (diagonalGenerator (R := R) 1)
      z hz'
  have hzero :
      a * diagonalGenerator (R := R) 0 +
          b * diagonalGenerator (R := R) 1 =
        relationGenerator F 0 := by
    exact (planarSecantData (F 0)).equation.symm
  have hone :
      c * diagonalGenerator (R := R) 0 +
          d * diagonalGenerator (R := R) 1 =
        relationGenerator F 1 := by
    exact (planarSecantData (F 1)).equation.symm
  rw [hzero, hone] at hmem
  change secantDet a b c d * z ∈ relationIdeal F
  apply
    (show
      Ideal.span
          ({relationGenerator F 0, relationGenerator F 1} :
            Set (PairRing R (Fin 2))) ≤
        relationIdeal F from ?_)
    hmem
  rw [Ideal.span_le]
  intro x hx
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
  rcases hx with rfl | rfl
  · exact Ideal.subset_span (Set.mem_range_self 0)
  · exact Ideal.subset_span (Set.mem_range_self 1)

/-- Over `ℂ`, the diagonal value of the chosen secant determinant is `planarJacobianDet`. -/
theorem diagonalEval_planarSecantDet_eq_planarJacobianDet
    (F : Fin 2 → PlanePolynomial) :
    diagonalEval (planarSecantDet F) =
      planarJacobianDet F := by
  exact diagonalEval_planarSecantDet F

/--
For a constant planar Jacobian `c`, the secant determinant is congruent to
the constant polynomial `c` modulo the diagonal ideal.
-/
theorem planarSecantDet_sub_constant_mem_diagonalIdeal
    (F : Fin 2 → PlanePolynomial)
    (c : ℂ)
    (hJacobian : planarJacobianDet F = C c) :
    planarSecantDet F - C c ∈
      diagonalIdeal (R := ℂ) (ι := Fin 2) := by
  rw [← diagonalEval_ker]
  change diagonalEval (planarSecantDet F - C c) = 0
  rw [map_sub, diagonalEval_planarSecantDet_eq_planarJacobianDet,
    hJacobian]
  simp [diagonalEval]

private noncomputable def pairConstantUnit
    (c : ℂ) (hc : c ≠ 0) :
    (PairRing ℂ (Fin 2))ˣ :=
  Units.map MvPolynomial.C.toMonoidHom (Units.mk0 c hc)

@[simp]
private theorem pairConstantUnit_val
    (c : ℂ) (hc : c ≠ 0) :
    (pairConstantUnit c hc : PairRing ℂ (Fin 2)) = C c := by
  rfl

/-- The collision equations together with the planar secant determinant. -/
noncomputable def planarSecantIdeal
    (F : Fin 2 → PlanePolynomial) :
    Ideal (PairRing ℂ (Fin 2)) :=
  relationIdeal F ⊔ Ideal.span {planarSecantDet F}

/--
For a planar Keller map, the canonical off-diagonal colon ideal is the
collision ideal together with the chosen secant determinant.
-/
theorem collisionOffDiagonalIdeal_eq_planarSecantIdeal
    (F : Fin 2 → PlanePolynomial)
    (hKeller : IsPlanarKeller F) :
    collisionOffDiagonalIdeal F =
      planarSecantIdeal F := by
  obtain ⟨c, hc, hJacobian⟩ := hKeller
  rw [collisionOffDiagonalIdeal, offDiagonalColonIdeal,
    planarSecantIdeal]
  apply colon_eq_sup_span_singleton_of_secant
    (relationIdeal F)
    (diagonalIdeal (R := ℂ) (ι := Fin 2))
    (planarSecantDet F)
    (pairConstantUnit c hc)
  · exact planarSecantDet_mul_diagonalIdeal_mem_relationIdeal F
  · simpa using
      planarSecantDet_sub_constant_mem_diagonalIdeal
        F c hJacobian

/--
For a planar Keller map, equality of the collision and diagonal ideals is
equivalent to the concrete secant ideal being the unit ideal.
-/
theorem relationIdeal_eq_diagonalIdeal_iff_planarSecantIdeal_eq_top
    (F : Fin 2 → PlanePolynomial)
    (hKeller : IsPlanarKeller F) :
    relationIdeal F =
        diagonalIdeal (R := ℂ) (ι := Fin 2) ↔
      planarSecantIdeal F = ⊤ := by
  obtain ⟨c, hc, hJacobian⟩ := hKeller
  rw [planarSecantIdeal]
  apply ideal_eq_iff_sup_span_singleton_eq_top_of_secant
    (relationIdeal F)
    (diagonalIdeal (R := ℂ) (ι := Fin 2))
    (planarSecantDet F)
    (pairConstantUnit c hc)
    (relationIdeal_le_diagonalIdeal F)
  · exact planarSecantDet_mul_diagonalIdeal_mem_relationIdeal F
  · simpa using
      planarSecantDet_sub_constant_mem_diagonalIdeal
        F c hJacobian

/--
For a planar Keller map, the obstruction vanishes exactly when the concrete
secant ideal is the unit ideal.
-/
theorem obstructionIdeal_eq_bot_iff_planarSecantIdeal_eq_top
    (F : Fin 2 → PlanePolynomial)
    (hKeller : IsPlanarKeller F) :
    obstructionIdeal F = ⊥ ↔
      planarSecantIdeal F = ⊤ := by
  exact
    (obstructionIdeal_eq_bot_iff F).trans
      (relationIdeal_eq_diagonalIdeal_iff_planarSecantIdeal_eq_top
        F hKeller)

/-- The unit-ideal formulation of the planar vanishing theorem target. -/
def PlanarSecantVanishing : Prop :=
  ∀ F : Fin 2 → PlanePolynomial,
    IsPlanarKeller F →
      planarSecantIdeal F = ⊤

/--
The concrete secant unit-ideal criterion is equivalent to planar vanishing.
-/
theorem planarSecantVanishing_iff_planarVanishing :
    PlanarSecantVanishing ↔ PlanarVanishing := by
  constructor
  · intro h F hKeller
    exact
      (obstructionIdeal_eq_bot_iff_planarSecantIdeal_eq_top
        F hKeller).2
        (h F hKeller)
  · intro h F hKeller
    exact
      (obstructionIdeal_eq_bot_iff_planarSecantIdeal_eq_top
        F hKeller).1
        (h F hKeller)

private noncomputable def collisionConstantUnit
    (F : Fin 2 → PlanePolynomial)
    (c : ℂ) (hc : c ≠ 0) :
    (CollisionRing F)ˣ :=
  Units.map
    (Ideal.Quotient.mk (relationIdeal F)).toMonoidHom
    (pairConstantUnit c hc)

@[simp]
private theorem collisionConstantUnit_val
    (F : Fin 2 → PlanePolynomial)
    (c : ℂ) (hc : c ≠ 0) :
    (collisionConstantUnit F c hc : CollisionRing F) =
      Ideal.Quotient.mk (relationIdeal F) (C c) := by
  rfl

/--
A planar Keller map supplies an explicit idempotent generator of its
off-diagonal obstruction in the collision ring.
-/
theorem exists_collisionOffDiagonalProjector_of_isPlanarKeller
    (F : Fin 2 → PlanePolynomial)
    (hKeller : IsPlanarKeller F) :
    ∃ q : CollisionRing F,
      IsCollisionOffDiagonalProjector F q := by
  obtain ⟨c, hc, hJacobian⟩ := hKeller
  let δbar : CollisionRing F :=
    Ideal.Quotient.mk (relationIdeal F) (planarSecantDet F)
  let cbar : (CollisionRing F)ˣ :=
    collisionConstantUnit F c hc
  have hδann :
      δbar ∈ (obstructionIdeal F).annihilator := by
    exact
      quotient_mk_mem_annihilator_obstruction
        (relationIdeal F)
        (diagonalIdeal (R := ℂ) (ι := Fin 2))
        (planarSecantDet F)
        (planarSecantDet_mul_diagonalIdeal_mem_relationIdeal F)
  have hann :
      ∀ j ∈ obstructionIdeal F, δbar * j = 0 := by
    intro j hj
    exact Submodule.mem_annihilator.mp hδann j hj
  have hmod :
      δbar - (cbar : CollisionRing F) ∈
        obstructionIdeal F := by
    have hsource :=
      planarSecantDet_sub_constant_mem_diagonalIdeal
        F c hJacobian
    exact
      Ideal.mem_map_of_mem
        (Ideal.Quotient.mk (relationIdeal F)) hsource
  refine
    ⟨offDiagonalIdempotent δbar cbar,
      offDiagonalIdempotent_isIdempotent
        (obstructionIdeal F) δbar cbar hann hmod,
      ?_⟩
  exact
    ideal_eq_span_offDiagonalIdempotent
      (obstructionIdeal F) δbar cbar hann hmod

/--
For a planar Keller map, the conventional saturation `I_R : I_Δ^∞` is the
same concrete secant ideal `I_R + (δ_F)`.
-/
theorem collisionIdealSaturation_eq_planarSecantIdeal
    (F : Fin 2 → PlanePolynomial)
    (hKeller : IsPlanarKeller F) :
    collisionIdealSaturation F =
      planarSecantIdeal F := by
  obtain ⟨q, hq⟩ :=
    exists_collisionOffDiagonalProjector_of_isPlanarKeller F hKeller
  exact
    (collisionIdealSaturation_eq_offDiagonalIdeal F q hq).trans
      (collisionOffDiagonalIdeal_eq_planarSecantIdeal F hKeller)

end

end CollisionIdeals
