import Mathlib.RingTheory.Ideal.Maps
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.RingTheory.Ideal.Span

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

universe u

variable {A : Type u} [CommRing A]

/--
The projector onto the off-diagonal summand.  Here `δ` is a secant
determinant and `c` is its invertible restriction to the diagonal.
-/
def offDiagonalIdempotent (δ : A) (c : Aˣ) : A :=
  1 - (↑(c⁻¹) : A) * δ

theorem offDiagonalIdempotent_mem
    (J : Ideal A) (δ : A) (c : Aˣ)
    (hmod : δ - (c : A) ∈ J) :
    offDiagonalIdempotent δ c ∈ J := by
  have hmul :
      (↑(c⁻¹) : A) * (δ - (c : A)) ∈ J :=
    J.mul_mem_left _ hmod
  have heq :
      offDiagonalIdempotent δ c =
        -((↑(c⁻¹) : A) * (δ - (c : A))) := by
    rw [offDiagonalIdempotent, mul_sub]
    simp
  rw [heq]
  exact J.neg_mem hmul

theorem offDiagonalIdempotent_mul
    (J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ j ∈ J, δ * j = 0)
    (j : A) (hj : j ∈ J) :
    offDiagonalIdempotent δ c * j = j := by
  calc
    offDiagonalIdempotent δ c * j =
        j - (↑(c⁻¹) : A) * (δ * j) := by
          simp only [offDiagonalIdempotent]
          ring
    _ = j := by rw [hann j hj, mul_zero, sub_zero]

/--
An annihilator congruent to a unit modulo `J` produces an idempotent
projector onto `J`.
-/
theorem offDiagonalIdempotent_isIdempotent
    (J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ j ∈ J, δ * j = 0)
    (hmod : δ - (c : A) ∈ J) :
    IsIdempotentElem (offDiagonalIdempotent δ c) := by
  rw [IsIdempotentElem]
  exact offDiagonalIdempotent_mul J δ c hann _
    (offDiagonalIdempotent_mem J δ c hmod)

/-- Under the secant hypotheses, `J` is the off-diagonal idempotent summand. -/
theorem ideal_eq_span_offDiagonalIdempotent
    (J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ j ∈ J, δ * j = 0)
    (hmod : δ - (c : A) ∈ J) :
    J = Ideal.span {offDiagonalIdempotent δ c} := by
  apply le_antisymm
  · intro j hj
    rw [Ideal.mem_span_singleton']
    refine ⟨j, ?_⟩
    rw [mul_comm]
    exact offDiagonalIdempotent_mul J δ c hann j hj
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    exact offDiagonalIdempotent_mem J δ c hmod

/--
The obstruction vanishes exactly when its off-diagonal projector vanishes.
-/
theorem ideal_eq_bot_iff_offDiagonalIdempotent_eq_zero
    (J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ j ∈ J, δ * j = 0)
    (hmod : δ - (c : A) ∈ J) :
    J = ⊥ ↔ offDiagonalIdempotent δ c = 0 := by
  rw [ideal_eq_span_offDiagonalIdempotent J δ c hann hmod,
    Ideal.span_singleton_eq_bot]

/--
The annihilator of the off-diagonal summand is generated by the
complementary diagonal projector.
-/
theorem annihilator_eq_span_one_sub_offDiagonalIdempotent
    (J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ j ∈ J, δ * j = 0)
    (hmod : δ - (c : A) ∈ J) :
    J.annihilator =
      Ideal.span {1 - offDiagonalIdempotent δ c} := by
  apply le_antisymm
  · intro r hr
    have hre : r * offDiagonalIdempotent δ c = 0 := by
      exact Submodule.mem_annihilator.mp hr _
        (offDiagonalIdempotent_mem J δ c hmod)
    rw [Ideal.mem_span_singleton']
    refine ⟨r, ?_⟩
    rw [mul_sub, mul_one, hre, sub_zero]
  · intro r hr
    rw [Ideal.mem_span_singleton'] at hr
    obtain ⟨a, rfl⟩ := hr
    apply Submodule.mem_annihilator.mpr
    intro j hj
    change (a * (1 - offDiagonalIdempotent δ c)) * j = 0
    rw [mul_assoc]
    have hej := offDiagonalIdempotent_mul J δ c hann j hj
    rw [sub_mul, one_mul, hej, sub_self, mul_zero]

/-- The determinant of a two-by-two secant matrix. -/
def secantDet (a b c d : A) : A :=
  a * d - b * c

/--
The adjugate identity before passing to the collision quotient:
`det(M) I_Δ ⊆ I_R`.
-/
theorem secantDet_mul_diagonalIdeal_mem_collisionIdeal
    (a b c d dx dy z : A)
    (hz : z ∈ Ideal.span ({dx, dy} : Set A)) :
    secantDet a b c d * z ∈
      Ideal.span ({a * dx + b * dy, c * dx + d * dy} : Set A) := by
  let I :=
    Ideal.span ({a * dx + b * dy, c * dx + d * dy} : Set A)
  have hdx : secantDet a b c d * dx ∈ I := by
    rw [Ideal.mem_span_pair]
    refine ⟨d, -b, ?_⟩
    simp only [secantDet]
    ring
  have hdy : secantDet a b c d * dy ∈ I := by
    rw [Ideal.mem_span_pair]
    refine ⟨-c, a, ?_⟩
    simp only [secantDet]
    ring
  obtain ⟨r, s, rfl⟩ := Ideal.mem_span_pair.mp hz
  change secantDet a b c d * (r * dx + s * dy) ∈ I
  rw [show secantDet a b c d * (r * dx + s * dy) =
      r * (secantDet a b c d * dx) +
        s * (secantDet a b c d * dy) by ring]
  exact I.add_mem (I.mul_mem_left r hdx) (I.mul_mem_left s hdy)

/-- Ideal containment descends to annihilation in the quotient ring. -/
theorem quotient_mk_mem_annihilator_obstruction
    (IR IΔ : Ideal A) (δ : A)
    (hδ : ∀ z ∈ IΔ, δ * z ∈ IR) :
    Ideal.Quotient.mk IR δ ∈
      (IΔ.map (Ideal.Quotient.mk IR)).annihilator := by
  apply Submodule.mem_annihilator.mpr
  intro q hq
  obtain ⟨z, hz, rfl⟩ :=
    (Ideal.mem_map_iff_of_surjective
      (Ideal.Quotient.mk IR) Ideal.Quotient.mk_surjective).mp hq
  change Ideal.Quotient.mk IR δ * Ideal.Quotient.mk IR z = 0
  rw [← map_mul]
  exact Ideal.Quotient.eq_zero_iff_mem.mpr (hδ z hz)

/-- The adjugate identity for the first diagonal generator. -/
theorem secantDet_mul_fst
    (a b c d dx dy : A)
    (h₁ : a * dx + b * dy = 0)
    (h₂ : c * dx + d * dy = 0) :
    secantDet a b c d * dx = 0 := by
  calc
    secantDet a b c d * dx =
        d * (a * dx + b * dy) - b * (c * dx + d * dy) := by
          simp only [secantDet]
          ring
    _ = 0 := by rw [h₁, h₂]; simp

/-- The adjugate identity for the second diagonal generator. -/
theorem secantDet_mul_snd
    (a b c d dx dy : A)
    (h₁ : a * dx + b * dy = 0)
    (h₂ : c * dx + d * dy = 0) :
    secantDet a b c d * dy = 0 := by
  calc
    secantDet a b c d * dy =
        a * (c * dx + d * dy) - c * (a * dx + b * dy) := by
          simp only [secantDet]
          ring
    _ = 0 := by rw [h₁, h₂]; simp

end

end CollisionIdeals
