import CollisionIdeals.ComplexThree.Basic
import CollisionIdeals.General.GenericFiber.FunctionField

/-!
# Function-field notation in complex dimension three

This file contains only the two function-field abbreviations consumed by
the structural cubic `S₃` collision theorem.  Normalization, valuation,
and inertia constructions remain in the dimension-independent modules
until a dimension-three theorem actually needs them.
-/

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

/-- The source function field `ℂ(x₁,x₂,x₃)`. -/
abbrev ComplexThreeSourceFunctionField :=
  PolynomialSourceFunctionField (R := ℂ) (ι := Fin 3)

/-- The function field generated by the three coordinates of `F`. -/
abbrev ComplexThreeBaseFunctionField
    (F : ComplexThreePolynomialMap) :=
  PolynomialBaseFunctionField F

end

end CollisionIdeals
