import CollisionIdeals.Planar.Secant.Algebra
import Mathlib.RingTheory.Ideal.Colon

set_option autoImplicit false

namespace CollisionIdeals

noncomputable section

universe u

/--
If `δ` annihilates `J / I` and is congruent modulo `J` to a unit, then
the colon ideal `I : J` is generated by `I` and `δ`.
-/
theorem colon_eq_sup_span_singleton_of_secant
    {A : Type u} [CommRing A]
    (I J : Ideal A) (δ : A) (c : Aˣ)
    (hann : ∀ z ∈ J, δ * z ∈ I)
    (hmod : δ - (c : A) ∈ J) :
    I.colon J = I ⊔ Ideal.span {δ} := by
  apply le_antisymm
  · intro x hx
    let K := I ⊔ Ideal.span {δ}
    have hxmod : x * (δ - (c : A)) ∈ I :=
      Submodule.mem_colon.mp hx _ hmod
    have hxdelta : x * δ ∈ Ideal.span ({δ} : Set A) := by
      rw [Ideal.mem_span_singleton']
      exact ⟨x, rfl⟩
    have hxc : x * (c : A) ∈ K := by
      have hsub :=
        K.sub_mem
          (show x * δ ∈ K from Ideal.mem_sup_right hxdelta)
          (show x * (δ - (c : A)) ∈ K from Ideal.mem_sup_left hxmod)
      convert hsub using 1
      ring
    have hinv := K.mul_mem_left (↑(c⁻¹) : A) hxc
    simpa [K, mul_assoc] using hinv
  · intro x hx
    obtain ⟨i, hi, d, hd, hid⟩ :=
      Submodule.mem_sup.mp hx
    rw [Ideal.mem_span_singleton'] at hd
    obtain ⟨a, rfl⟩ := hd
    subst x
    apply Submodule.mem_colon.mpr
    intro z hz
    change (i + a * δ) * z ∈ I
    rw [add_mul, mul_assoc]
    exact I.add_mem
      (I.mul_mem_right z hi)
      (I.mul_mem_left a (hann z hz))

/--
Under `I ≤ J`, the same secant hypotheses identify `I = J` with the
unit-ideal condition `I + (δ) = A`.
-/
theorem ideal_eq_iff_sup_span_singleton_eq_top_of_secant
    {A : Type u} [CommRing A]
    (I J : Ideal A) (δ : A) (c : Aˣ)
    (hIJ : I ≤ J)
    (hann : ∀ z ∈ J, δ * z ∈ I)
    (hmod : δ - (c : A) ∈ J) :
    I = J ↔ I ⊔ Ideal.span {δ} = ⊤ := by
  constructor
  · intro h
    rw [Ideal.eq_top_iff_one]
    let K := I ⊔ Ideal.span {δ}
    have hδ : δ ∈ K :=
      Ideal.mem_sup_right
        (Ideal.mem_span_singleton_self δ)
    have hδc : δ - (c : A) ∈ K :=
      Ideal.mem_sup_left (by simpa [h] using hmod)
    have hc : (c : A) ∈ K := by
      have := K.sub_mem hδ hδc
      convert this using 1
      ring
    have hinv := K.mul_mem_left (↑(c⁻¹) : A) hc
    simpa [K, mul_assoc] using hinv
  · intro htop
    apply le_antisymm hIJ
    intro z hz
    have hone : (1 : A) ∈ I ⊔ Ideal.span {δ} := by
      rw [htop]
      trivial
    obtain ⟨r, hr, d, hd, hrd⟩ :=
      Submodule.mem_sup.mp hone
    rw [Ideal.mem_span_singleton'] at hd
    obtain ⟨a, rfl⟩ := hd
    have hzEq : z = r * z + a * (δ * z) := by
      calc
        z = 1 * z := by rw [one_mul]
        _ = (r + a * δ) * z := by rw [hrd]
        _ = r * z + a * (δ * z) := by ring
    rw [hzEq]
    exact I.add_mem
      (I.mul_mem_right z hr)
      (I.mul_mem_left a (hann z hz))

end

end CollisionIdeals
